#pragma once

namespace hsbg {
	enum class id : int {
		// Tier 1
		alleycat = 0,
		dire_wolf_alpha,
		dragonspawn_lieutenant,
		fiendish_servant,
		vulgar_homunculus,
		mecharoo,
		micro_machine,
		murloc_tidecaller,
		murloc_tidehunter,
		red_whelp,
		rockpool_hunter,
		righteous_protector,
		selfless_hero,
		wrath_weaver,
		// Tokens (tier 1)
		big_bad_wolf,
		damaged_golem,
		finkle_einhorn,
		guard_bot,
		hyena,
		imp,
		ironhide_runt,
		jo_e_bot,
		microbot,
		murloc_scout,
		plant,
		rat,
		robosaur,
		spider,
		tabbycat,
		voidwalker,
		amalgam,
		// Tier 2
		glyph_guardian,
		harvest_golem,
		imprisoner,
		kaboom_bot,
		kindly_grandmother,
		metaltooth_leaper,
		murloc_warleader,
		nathrezim_overseer,
		old_murk_eye,
		pogo_hopper,
		rat_pack,
		scavenging_hyena,
		spawn_of_nzoth,
		steward_of_time,
		unstable_ghoul,
		waxrider_togwaggle,
		zoobot,
		// Tier 3
		bronze_warden,
		cobalt_guardian,
		coldlight_seer,
		crowd_favorite,
		crystal_weaver,
		deflect_o_bot,
		felfin_navigator,
		hangry_dragon,
		houndmaster,
		imp_gang_boss,
		infested_wolf,
		khadgar,
		pack_leader,
		piloted_shredder,
		replicating_menace,
		screwjank_clunker,
		shifter_zerus,
		soul_juggler,
		the_beast,
		twilight_emissary,
		// Tier 4
		annoy_o_module,
		bolvar_fireblood,
		cave_hydra,
		cobalt_scalebane,
		defender_of_argus,
		drakonid_enforcer,
		floating_watcher,
		herald_of_flame,
		iron_sensei,
		mechano_egg,
		menagerie_magician,
		savannah_highmane,
		security_rover,
		siegebreaker,
		toxfin,
		virmen_sensei,
		// Tier 5
		annihilan_battlemaster,
		baron_rivendare,
		brann_bronzebeard,
		goldrinn_the_great_wolf,
		ironhide_direhorn,
		junkbot,
		king_bagurgle,
		lightfang_enforcer,
		malganis,
		murozond,
		primalfin_lookout,
		razorgore_the_untamed,
		sneeds_old_shredder,
		strongshell_scavenger,
		voidlord,
		// Tier 6
		foe_reaper_4000,
		gentle_megasaur,
		ghastcoiler,
		holy_mackerel,
		imp_mama,
		kangors_apprentice,
		kalecgos_arcane_aspect,
		maexxna,
		mama_bear,
		nadina_the_red,
		zapp_slywick,
		// Used to get the number of minion IDs. Must be the last value.
		COUNT
	};
}
